<footer>
    <div class="footer-content">
        <section class="footer-links">
            <h3>Project Links</h3>
            <p><a href="https://appliedwebproject-g03.atlassian.net" target="_blank">Jira Project Board</a></p>
            <p><a href="https://github.com/106507468/group-part2" target="_blank">GitHub Repository</a></p>
        </section>
        <section class="footer-contacts">
            <h2>Contact us</h2>
            <p>Email: <a href="mailto:info@ecosolutions.com.au">info@ecosolutions.com.au</a></p>
        </section>
        <p class="footer-copy">&copy; 2026 Ecosolutions. All rights reserved.</p>
    </div>
</footer>
