<header>
    <img src="images/logo.jpg" alt="EcoSolutions logo" width="35%">
    <nav>
        <a href="index.php">Home</a>
        <a href="jobs.php">Jobs</a>
        <a href="apply.php">Apply</a>
        <a href="about.php">About</a>
    </nav>
    <div class="search-bar">
        <input type="text" placeholder="Search..."/>
        <button>Search</button>
    </div>
    <div class="login"> 
    <a href="login.php"> <button type="button">Login</button> </a>
    </div>
</header>