<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="description" content="Showcases two job descriptions for Ecosolutions, an environmental technological company">
        <meta name="keywords" content="Job, Career, Ecosolutions, Web Developer, Digital Project Coordinator">
        <meta name="author" content="Sreetoma Deb Roy, WWW(Worldwide Women)">
        <title>Jobs Page</title>
        <link rel="stylesheet" href="styles.css">
        <!--- Internal CSS-->
        <style>
            /* This styles the page title */
            main h1 {
                text-align: center;
                color: #0C4F29;
            }
        </style>
    </head>
    

    <body>
    
    <?php include 'header.inc'; ?>
       
    <main>  
        <h1>Ecosolutions Careers</h1>
            <aside>
                <h2>Why Work With Us?</h2>
                <p><em>
                    At EcoSolutions, we are committed to building a sustainable future 
                    through innovative renewable energy technologies. 
                </em></p>
            </aside>
            <form action="jobs.php" method="get">
                <div class="search-bar">
                    <input type="text" name="search"
                        placeholder="Search by title, reference or salary..."
                        value="<?php echo isset($_GET['search']) ? htmlspecialchars($_GET['search']) : ''; ?>">
                    <button type="submit">Search</button>
                </div>
            </form>
           <?php
            require_once('settings.php');

            if (isset($_GET['search'])) {
                $search = $conn->real_escape_string($_GET['search']);
                $query = "SELECT * FROM jobs WHERE job_title LIKE '%$search%' OR job_ref LIKE '%$search%'";
            } else {
                $query = "SELECT * FROM jobs";
            }

            $result = $conn->query($query);

            while ($row = $result->fetch_assoc()) {
            ?>
            

            <!--Job Description-->
            <section class="Job1">
                <!--Job Description (Generated by ChatGPT)-->
                <h2><?php echo $row['job_title']; ?></h2>
                <p><em><?php echo $row['job_des']; ?></em></p>
                <!--Inline CSS-->
                <h3 style="color:#0C4F29;">Reference: <?php echo $row['job_ref']; ?></h3>

                <p><strong>Salary: <?php echo $row['salary']; ?></strong></p>
                <p><strong>Reports to: <?php echo $row['reports_to']; ?></strong></p>

                <!-- Ordered list -->
                <h3>Key Responsibilities</h3>
                <ol>
                    <?php
                    $resp_items = explode("\n", $row['resp']);
                    foreach ($resp_items as $item) {
                        echo "<li>" . trim($item) . "</li>";
                    }
                    ?>
                </ol>

                <!-- Unordered list (Essential Requirements sourced from https://www.seek.com.au) -->
                <h3>Essential Requirements</h3>
                <ul>
                    <?php
                    $ess_items = explode("\n", $row['ess_req']);
                    foreach ($ess_items as $item) {
                        echo "<li>" . trim($item) . "</li>";
                    }
                    ?>
                </ul>

                <h3>Preferable Requirements</h3>
                <ul>
                    <?php
                    $pref_items = explode("\n", $row['pref_req']);
                    foreach ($pref_items as $item) {
                        echo "<li>" . trim($item) . "</li>";
                    }
                    ?>
                </ul>
            </section>
        <?php
        }

        $conn->close();
        ?>

    </main> 

    <?php include 'footer.inc'; ?>

    </body>
</html>
