<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="description" content="Showcases two job descriptions for Ecosolutions, an environmental technological company">
        <meta name="keywords" content="Job, Career, Ecosolutions, Web Developer, Digital Project Coordinator">
        <meta name="author" content="Sreetoma Deb Roy, WWW(Worldwide Women)">
        <title>Jobs Page</title>
        <link rel="stylesheet" href="styles.css">
        <!--- Internal CSS-->
        <style>
            /* This styles the page title */
            main h1 {
                text-align: center;
                color: #0C4F29;
            }
        </style>
    </head>
    

    <body>
        <header>
                <img src="images/logo.jpg" width="35%" alt="company logo">
                    <nav>
                        <a href="index.html">Home</a>
                        <a href="jobs.html">Jobs</a>
                        <a href="apply.html">Apply</a>
                        <a href="about.html">About</a>
                    </nav>
                    <div class="search-bar">
                    <input type="text" placeholder="Search..." />
                    <button>Search</button>
                </div>
        </header>
        
       
    <main>  
        <h1>Ecosolutions Careers</h1>
            <aside>
                <h2>Why Work With Us?</h2>
                <p><em>
                    At EcoSolutions, we are committed to building a sustainable future 
                    through innovative renewable energy technologies. 
                </em></p>
            </aside>

            <!--Job Description 1-->
            <section class="Job1"> 
                <!--Job Description (Generated by ChatGPT)-->
                <h2>Renewable Energy Web Developer</h2> 
                <p><em>Join our tech team as a Rebewable Energy Web Developer to develop platforms promoting clean energy solutions.</em></p>
                <!--Inline CSS-->
                <h3 style="color:#0C4F29;">Reference: RE439</h3> 

                <p><strong>Salary: $80,000 - $100,000</strong></p>
                <p><strong>Reports to: Senior Developer</strong></p>
            

                <!-- Ordered list -->
                <h3>Key Responsibilities</h3>
                <ol>
                    <li>Develop and maintain company websites.</li>
                    <li>Collaborate with designers and engineers.</li>
                    <li>Ensure accessibility and responsiveness.</li>
                </ol>

                <!-- Unordered list (Essential Requirements sourced from https://www.seek.com.au) -->
                <h3>Essential Requirements</h3>
                <ul>
                    <li>Bachelor's or equivalent in the relevant field.</li>
                    <li>At least 2 years of relevant experience in Web Development.</li>
                    <li>Team collaboration skills.</li>
                </ul>

                <h3>Preferable Requirements</h3>
                <ul>
                    <li>Experience in renewable energy sector.</li>
                    <li>UI/UX design knowledge.</li>
                </ul>
            </section>


            <!--Job Description 2-->
            <section class="Job2">
                <!--Job Description (Generated by ChatGPT)-->
                <h2>Digital Project Coordinator</h2>
                <p><em> As a Digital Project Coordinator at Ecosolutions you will coordinate digital projects supporting sustainable energy initiatives.
                </em></p>
                <!--Inline CSS-->
                <h3 style="color:#0C4F29;">Reference: RE528</h3>

                <p><strong>Salary: $70,000 - $90,000</strong></p>
                <p><strong>Reports to: Project Manager</strong></p>
            

                <!-- Ordered list -->
                <h3>Key Responsibilities</h3> 
                <ol>
                    <li>Manage project timelines.</li>
                    <li>Communicate with stakeholders.</li>
                    <li>Track project progress using tools like Jira.</li>
                </ol>

                <!-- Unordered list (Essential Requirements sourced from https://www.seek.com.au) -->
                <h3>Essential Requirements</h3>
                <ul>
                    <li>2-3 years' experience in project coordination or project administration.</li>
                    <li>Confidence working with stakeholders and cross functional internal teams.</li>
                    <li>Sound technical understanding.</li>
                </ul>

                <h3>Preferable Requirements</h3>
                <ul>
                    <li>Experience with Agile methodology.</li>
                    <li>Knowledge of sustainability projects.</li>
                </ul>
             </section>
    </main> 

    <footer>
        <p>&copy; 2026 EcoSolutions. All rights reserved.</p>
    </footer>

    </body>
</html>
