 <?php
    session_start();
    // Redirect to login if not logged in
    if (!isset($_SESSION['username'])) {
        header("Location: login.php");
        exit();
    }
    
    // Logout
    if (isset($_GET['logout'])) {
        session_unset();
        session_destroy();
        header("Location: login.php");
        exit();
    }
    
    require_once('settings.php');
?>    

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Manager Dashboard for Ecosolutions">
    <meta name="author" content="Sreetoma Deb Roy, WWW(Worldwide Women)">
    <title>Manager - Manage EOIs</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <?php include 'header.inc'; ?>
<main>
    <h3>HR Manager Dashboard</h3>
    <a href="manage.php?logout=1">Logout</a>
 
<h2>Search EOIs</h2>
    <form method="get" action="manage.php">
 
        <label for="filter_ref">Job Reference</label>
        <input type="text" id="filter_ref" name="filter_ref" placeholder="e.g. RE439"
            value="<?php echo isset($_GET['filter_ref'])?htmlspecialchars($_GET['filter_ref']) : ''; ?>">
 
        <label for="filter_name">Applicant Name</label>
        <input type="text" id="filter_name" name="filter_name" placeholder="e.g. Jane Smith"
            value="<?php echo isset($_GET['filter_name'])?htmlspecialchars($_GET['filter_name']) : ''; ?>">
 
        <label for="sort_by">Sort by</label>
        <select id="sort_by" name="sort_by">
            <option value="EOInumber"<?php echo (isset($_GET['sort_by']) && $_GET['sort_by'] == 'EOInumber')? 'selected' : ''; ?>>EOI Number</option> //Generated by ChatGPT
            <option value="job_reference"<?php echo (isset($_GET['sort_by']) && $_GET['sort_by'] == 'job_reference')? 'selected' : ''; ?>>Job Reference</option>
            <option value="first_name"<?php echo (isset($_GET['sort_by']) && $_GET['sort_by'] == 'first_name')? 'selected' : ''; ?>>First Name</option>
            <option value="last_name"<?php echo (isset($_GET['sort_by']) && $_GET['sort_by'] == 'last_name')? 'selected' : ''; ?>>Last Name</option>
            <option value="status"<?php echo(isset($_GET['sort_by']) && $_GET['sort_by'] == 'status')? 'selected' : ''; ?>>Status</option>
        </select>
        <button type="submit" name="list_all" value="1">Search</button>
    </form>
 
    <!-- Delete EOIs by job reference — separate POST form -->
    <h2>Delete EOIs by Job Reference</h2>
    <p>Warning: This will permanently delete all EOIs for the entered job reference.</p>
    <form method="post" action="manage.php">
        <input type="hidden" name="action" value="delete_by_ref">
        <label for="delete_ref">Job Reference</label>
        <input type="text" id="delete_ref" name="delete_ref" placeholder="e.g. RE439" required>
        <button type="submit">Delete All EOIs</button>
    </form>
 





    <?php include 'footer.inc'; ?>

</body>
</html>