 <?php
    session_start();
    // Redirect to login if not logged in
    if (!isset($_SESSION['username'])) {
        header("Location: login.php");
        exit();
    }
    
    // Logout
    if (isset($_GET['logout'])) {
        session_unset();
        session_destroy();
        header("Location: login.php");
        exit();
    }
    
    require_once('settings.php');
?>    

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Manager Dashboard for Ecosolutions">
    <meta name="author" content="Sreetoma Deb Roy, WWW(Worldwide Women)">
    <title>Manager - Manage EOIs</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <?php include 'header.inc'; ?>
<main>
        <h3>HR Manager Dashboard</h3>
        <a href="manage.php?logout=1">Logout</a>
    
    <h2>Search EOIs</h2>
    <div class="form-pref">
        <form method="get" action="manage.php">
    
            <label for="filter_ref">Job Reference</label>
            <input type="text" id="filter_ref" name="filter_ref" placeholder="e.g. RE439"
                value="<?php echo isset($_GET['filter_ref'])?htmlspecialchars($_GET['filter_ref']):'';?>">
    
            <label for="filter_name">Applicant Name</label>
            <input type="text" id="filter_name" name="filter_name" placeholder="e.g. Jane Smith"
                value="<?php echo isset($_GET['filter_name'])?htmlspecialchars($_GET['filter_name']):'';?>">
    
            <label for="sort_by">Sort by</label>
            <select id="sort_by" name="sort_by">
            <!-- The following php codes for each option was generated by ChatGPT -->
                <option value="EOInumber"<?php echo (isset($_GET['sort_by']) && $_GET['sort_by'] == 'EOInumber')?'selected': ''; ?>>EOI Number</option> 
                <option value="job_reference"<?php echo (isset($_GET['sort_by']) && $_GET['sort_by'] == 'job_reference')?'selected':''; ?>>Job Reference</option> 
                <option value="first_name"<?php echo (isset($_GET['sort_by']) && $_GET['sort_by'] == 'first_name')?'selected':''; ?>>First Name</option> 
                <option value="last_name"<?php echo (isset($_GET['sort_by']) && $_GET['sort_by'] == 'last_name')?'selected':''; ?>>Last Name</option> 
                <option value="status"<?php echo(isset($_GET['sort_by']) && $_GET['sort_by'] == 'status')?'selected':''; ?>>Status</option>
            </select>    
            <button type="submit" name="list_all" value="1">Search</button>
        </form>
    </div>

        <!-- Delete EOIs by job reference -->
        <h2>Delete EOIs by Job Reference</h2>
        <p>Warning: This will permanently delete all EOIs for the entered job reference.</p>
        <div class="form-del">
            <form method="post" action="manage.php">
                <input type="hidden" name="action" value="delete_by_ref">
                <label for="delete_ref">Job Reference</label>
                <input type="text" id="delete_ref" name="delete_ref" placeholder="e.g. RE439" required>
                <button type="submit">Delete All EOIs</button>
            </form>
        </div>
        <?php
            // Delete all EOIs by job reference 
            if ($_SERVER['REQUEST_METHOD'] == 'POST' && $_POST['action'] == 'delete_by_ref') {
                $delRef = $conn->real_escape_string($_POST['delete_ref']);
                $query  = "DELETE FROM eoi WHERE job_reference = '$delRef'";
                $conn->query($query);
                echo "<p>EOIs for job reference " . $delRef . " have been deleted.</p>";
            }
            // Get the EOI number and new status from the form
            if ($_SERVER['REQUEST_METHOD'] == 'POST' && $_POST['action'] == 'change_status') {
                $eoiNum    = $_POST['eoi_number'];
                $newStatus = $conn->real_escape_string($_POST['new_status']);
             // Update the status in the database for the matching EOI
                $query     = "UPDATE eoi SET status = '$newStatus' WHERE EOInumber = '$eoiNum'";
                $conn->query($query);
                echo "<p>EOI #$eoiNum status updated to $newStatus.</p>";
            }
            // Set the default sort column to EOInumber
            $sortBy = 'EOInumber';
            $allowedSort = ['EOInumber', 'job_reference', 'first_name', 'last_name', 'status'];
            if (isset($_GET['sort_by']) && in_array($_GET['sort_by'], $allowedSort)) {
                $sortBy = $_GET['sort_by'];
            }
            // No filter by default it will show all EOIs
            $where = "";
            
            // If searched by job reference, filter by reference number
            if (!empty($_GET['filter_ref'])) {
                $ref   = $conn->real_escape_string($_GET['filter_ref']);
                $where = "WHERE job_reference = '$ref'";
            }

            // If searched by name, check both first and last name columns
            if (!empty($_GET['filter_name'])) {
                $name  = $conn->real_escape_string($_GET['filter_name']);
                $where = "WHERE first_name LIKE '%$name%' OR last_name LIKE '%$name%'";
            }
            // Show results
            if (isset($_GET['list_all']) || !empty($_GET['filter_ref']) || !empty($_GET['filter_name'])) {

                $query  = "SELECT * FROM eoi $where ORDER BY $sortBy";
                $result = $conn->query($query);
                // The following code for the Results table was Generated By ChatGPT
                echo "<h2>Results</h2>"; 
                echo "<table>";
                echo "<tr>
                        <th>EOI #</th>
                        <th>Job Ref</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Status</th>
                        <th>Change Status</th>
                    </tr>";
                // The following code and form was Generated By ChatGPT which ends at the curly bracket
                while ($row = $result->fetch_assoc()) { 
                    echo "<tr>"; 
                    echo "<td>" .$row['EOInumber']. "</td>";
                    echo "<td>" .$row['job_reference']. "</td>";
                    echo "<td>" .$row['first_name']. "</td>";
                    echo "<td>" .$row['last_name']. "</td>";
                    echo "<td>" .$row['email']. "</td>";
                    echo "<td>" .$row['phone']. "</td>";
                    echo "<td>" .$row['status']. "</td>";
                    echo "<td>
                            <form method='post' action='manage.php'> 
                                <input type='hidden' name='action' value='change_status'>
                                <input type='hidden' name='eoi_number' value='".$row['EOInumber']. "'>
                                <select name='new_status'>
                                    <option value='New'>New</option>
                                    <option value='Current'>Current</option>
                                    <option value='Final'>Final</option>
                                </select>
                                <button type='submit'>Update</button>
                            </form>
                            </td>";
                        echo "</tr>";
                        }
                        echo "</table>";
                    }
                $conn->close();
        ?>
 
</main>
        
    <?php include 'footer.inc'; ?>

</body>
</html>